package selenium.exercise;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Locators {
    public static void main(String[] args) {
        WebDriver driver = new ChromeDriver();
        driver.get("https://rahulshettyacademy.com/locatorspractice");
        
        //find by id, can find by other things (e.g., xpath, class, etc)
        driver.findElement(By.id("inputUsername")).sendKeys("gloria"); 
        //type gloria inside the id inputUsername

        //find by name
        driver.findElement(By.name("password")).sendKeys("12345");
        driver.findElement(By.className("submit")).click();

        //find by css class
        //constructing css class selector: tagname.classname -> if ID, change (.) to (#)
        //e.g.: <p class="error">this is an error</p> -> the css class selector will be p.error
        //e.g.: <p id=info">this is an info</p> -> the css id selector will be p#info

        //generic css class selector: tagname[attribute='value'] -> if there's no id or class, can be helpful for more generic classes such as classes generated by bootstrap
        //e.g.: <input type="text" placeholder="search" value=""/> -> css selector will be input[placeholder="search"], OR input[type="text"]. but due to Selenium's behaviour (reads from top to bottom and then select the first matching element), selector HAS TO be unique. selectorhub (chrome extension) can help determining whether the selector is unique.
        
       String errorMsg =  driver.findElement(By.cssSelector("p.error")).getText();
       System.out.println(errorMsg);
    }
}
